# CodeRabbit Configuration for GraFx Studio Workspace
# Merged organizational defaults with project-specific settings

language: en-US
tone_instructions: ''
early_access: false
enable_free_tier: false

reviews:
    # Organizational settings
    profile: chill
    request_changes_workflow: false
    high_level_summary: true
    high_level_summary_placeholder: '@coderabbitai summary'
    high_level_summary_in_walkthrough: true
    auto_title_placeholder: '@coderabbitai'
    auto_title_instructions: ''
    review_status: true
    commit_status: true
    fail_commit_status: false
    collapse_walkthrough: false
    changed_files_summary: true
    sequence_diagrams: true
    estimate_code_review_effort: true
    assess_linked_issues: true
    related_issues: true
    related_prs: true
    suggested_labels: false
    labeling_instructions: []
    auto_apply_labels: false
    suggested_reviewers: false
    auto_assign_reviewers: false
    in_progress_fortune: true
    poem: false
    path_filters: []
    path_instructions:
        - path: ''
          instructions: ''
    abort_on_close: false
    disable_cache: false

    # Auto-review configuration with project-specific patterns
    auto_review:
        enabled: true
        auto_incremental_review: true
        ignore_title_keywords: []
        labels: []
        drafts: false
        base_branches: []
        ignore_usernames: []

# Project-specific finishing touches
finishing_touches:
    docstrings:
        enabled: false
    unit_tests:
        enabled: true

# Pre-merge checks with project standards
pre_merge_checks:
    title:
        mode: warning
        requirements: ''
    description:
        mode: warning
    issue_assessment:
        mode: warning
    custom_checks: []

# Tools - keeping organizational defaults but focusing on relevant ones for TypeScript/React
tools:
    # Essential tools for the project
    eslint:
        enabled: true
    github-checks:
        enabled: true
        timeout_ms: 90000
    gitleaks:
        enabled: true
    semgrep:
        enabled: true

    # Language-specific tools (disabled for non-relevant languages)
    ruff:
        enabled: false # Python
    shellcheck:
        enabled: false # Shell scripts
    biome:
        enabled: false # Alternative to ESLint, we use ESLint
    golangci-lint:
        enabled: false # Go
    clippy:
        enabled: false # Rust
    swiftlint:
        enabled: false # Swift
    phpstan:
        enabled: false # PHP
    phpmd:
        enabled: false # PHP
    phpcs:
        enabled: false # PHP
    detekt:
        enabled: false # Kotlin
    rubocop:
        enabled: false # Ruby
    flake8:
        enabled: false # Python
    pylint:
        enabled: false # Python
    luacheck:
        enabled: false # Lua
    brakeman:
        enabled: false # Ruby
    buf:
        enabled: false # Protocol buffers
    regal:
        enabled: false # Rego
    pmd:
        enabled: false # Java
    clang:
        enabled: false # C/C++
    cppcheck:
        enabled: false # C/C++
    sqlfluff:
        enabled: false # SQL
    prismaLint:
        enabled: false # Prisma
    oxc:
        enabled: false # Alternative JavaScript linter
    shopifyThemeCheck:
        enabled: false # Shopify themes
    dotenvLint:
        enabled: false # Environment files
    htmlhint:
        enabled: false # HTML
    checkmake:
        enabled: false # Makefiles
    osvScanner:
        enabled: false # Vulnerability scanner for other languages

    # Infrastructure tools (keeping some for CI/CD)
    actionlint:
        enabled: true # GitHub Actions
    yamllint:
        enabled: true # YAML files

# Chat and integrations (keeping organizational settings)
chat:
    art: true
    auto_reply: true
    integrations:
        jira:
            usage: auto
        linear:
            usage: auto

# Knowledge base (organizational settings)
knowledge_base:
    opt_out: false
    web_search:
        enabled: true
    code_guidelines:
        enabled: true
        filePatterns: []
    learnings:
        scope: auto
    issues:
        scope: auto
    jira:
        usage: auto
        project_keys:
            - GRAFX
            - DT
            - CPAAS
            - FT
            - WRS
            - EDT
            - MAIN
            - PRODUCT
    linear:
        usage: auto
        team_keys: []
    pull_requests:
        scope: auto
    mcp:
        usage: auto
        disabled_servers: []

# Code generation (organizational settings)
code_generation:
    unit_tests:
        path_instructions: []
