export const LARGE_DATASET = [
    {
        firstName: 'Husein',
        lastName: 'Nears',
        email: 'hnears0@dot.gov',
        jobTitle: 'Assistant Media Planner',
        shirtSize: '3XL',
        title: 'Mrs',
        suffix: 'Jr',
    },
    {
        firstName: 'Lindsey LindseyBlaber LindseyBlaberBlaberBlaberBlaberBlaber',
        lastName: 'Blaber',
        email: 'lblaber1@elegantthemes.com',
        jobTitle: 'Tax Accountant',
        shirtSize: 'L',
        title: 'Mrs',
        suffix: 'Jr',
    },
    {
        firstName: 'Josefa',
        lastName: 'Cohen',
        email: 'jcohen2@mail.ru',
        jobTitle: 'Software Consultant',
        shirtSize: 'L',
        title: 'Mr',
        suffix: 'III',
    },
    {
        firstName: 'Laryssa',
        lastName: 'Skarr',
        email: 'lskarr3@rakuten.co.jp',
        jobTitle: 'Automation Specialist IV',
        shirtSize: 'M',
        title: 'Rev',
        suffix: 'Jr',
    },
    {
        firstName: 'Barret',
        lastName: 'Christon',
        email: 'bchriston4@tinyurl.com',
        jobTitle: 'Software Test Engineer I',
        shirtSize: '3XL',
        title: 'Rev',
        suffix: 'II',
    },
    {
        firstName: 'Inesita',
        lastName: 'Obington',
        email: 'iobington5@nydailynews.com',
        jobTitle: 'Librarian',
        shirtSize: 'M',
        title: 'Honorable',
        suffix: 'II',
    },
    {
        firstName: 'Teddy',
        lastName: 'Portingale',
        email: 'tportingale6@topsy.com',
        jobTitle: 'Environmental Tech',
        shirtSize: 'S',
        title: 'Ms',
        suffix: 'II',
    },
    {
        firstName: 'Jeramie',
        lastName: 'Gipp',
        email: 'jgipp7@uiuc.edu',
        jobTitle: 'Research Associate',
        shirtSize: 'M',
        title: 'Mrs',
        suffix: 'II',
    },
    {
        firstName: 'Meggy',
        lastName: 'Aingell',
        email: 'maingell8@stumbleupon.com',
        jobTitle: 'Account Executive',
        shirtSize: 'XL',
        title: 'Mrs',
        suffix: 'II',
    },
    {
        firstName: 'Janie',
        lastName: 'Popplestone',
        email: 'jpopplestone9@accuweather.com',
        jobTitle: 'Data Coordinator',
        shirtSize: 'S',
        title: 'Ms',
        suffix: 'IV',
    },
    {
        firstName: 'Conrado',
        lastName: 'Bouldon',
        email: 'cbouldona@printfriendly.com',
        jobTitle: 'Data Coordinator',
        shirtSize: 'M',
        title: 'Rev',
        suffix: 'IV',
    },
    {
        firstName: 'Neysa',
        lastName: 'Semeniuk',
        email: 'nsemeniukb@deviantart.com',
        jobTitle: 'Chemical Engineer',
        shirtSize: 'L',
        title: 'Honorable',
        suffix: 'II',
    },
    {
        firstName: 'Cass',
        lastName: 'Roxburgh',
        email: 'croxburghc@webnode.com',
        jobTitle: 'Systems Administrator IV',
        shirtSize: '2XL',
        title: 'Rev',
        suffix: 'III',
    },
    {
        firstName: 'Gweneth',
        lastName: 'Winman',
        email: 'gwinmand@godaddy.com',
        jobTitle: 'Research Nurse',
        shirtSize: '2XL',
        title: 'Ms',
        suffix: 'Jr',
    },
    {
        firstName: 'Paulo',
        lastName: 'Meece',
        email: 'pmeecee@youku.com',
        jobTitle: 'Pharmacist',
        shirtSize: 'S',
        title: 'Ms',
        suffix: 'II',
    },
    {
        firstName: 'Jemima',
        lastName: 'Kulic',
        email: 'jkulicf@businesswire.com',
        jobTitle: 'Electrical Engineer',
        shirtSize: '3XL',
        title: 'Ms',
        suffix: 'III',
    },
    {
        firstName: 'Luise',
        lastName: 'Middup',
        email: 'lmiddupg@google.com.br',
        jobTitle: 'VP Product Management',
        shirtSize: 'S',
        title: 'Rev',
        suffix: 'IV',
    },
    {
        firstName: 'Audra',
        lastName: 'Rabier',
        email: 'arabierh@disqus.com',
        jobTitle: 'Structural Engineer',
        shirtSize: 'M',
        title: 'Mrs',
        suffix: 'III',
    },
    {
        firstName: 'Obadiah',
        lastName: 'Willshee',
        email: 'owillsheei@surveymonkey.com',
        jobTitle: 'Technical Writer',
        shirtSize: 'XS',
        title: 'Honorable',
        suffix: 'Jr',
    },
    {
        firstName: 'Elvera',
        lastName: 'Liddiatt',
        email: 'eliddiattj@eepurl.com',
        jobTitle: 'Actuary',
        shirtSize: '3XL',
        title: 'Mr',
        suffix: 'IV',
    },
    {
        firstName: 'Aloisia',
        lastName: 'Burris',
        email: 'aburrisk@devhub.com',
        jobTitle: 'Nurse',
        shirtSize: 'XL',
        title: 'Rev',
        suffix: 'II',
    },
    {
        firstName: 'Gilburt',
        lastName: 'Crackett',
        email: 'gcrackettl@indiegogo.com',
        jobTitle: 'Chief Design Engineer',
        shirtSize: 'M',
        title: 'Rev',
        suffix: 'Sr',
    },
    {
        firstName: 'Aldwin',
        lastName: 'Gherardi',
        email: 'agherardim@jiathis.com',
        jobTitle: 'Senior Editor',
        shirtSize: 'L',
        title: 'Honorable',
        suffix: 'Sr',
    },
    {
        firstName: 'Catherine',
        lastName: 'Mulbry',
        email: 'cmulbryn@scientificamerican.com',
        jobTitle: 'Data Coordinator',
        shirtSize: 'M',
        title: 'Ms',
        suffix: 'Sr',
    },
    {
        firstName: 'Sari',
        lastName: 'Botwright',
        email: 'sbotwrighto@usatoday.com',
        jobTitle: 'Geologist III',
        shirtSize: '3XL',
        title: 'Honorable',
        suffix: 'III',
    },
    {
        firstName: 'Chaim',
        lastName: 'Jouannin',
        email: 'cjouanninp@dailymotion.com',
        jobTitle: 'Editor',
        shirtSize: '2XL',
        title: 'Rev',
        suffix: 'Jr',
    },
    {
        firstName: 'Ruperta',
        lastName: 'Sheehy',
        email: 'rsheehyq@theglobeandmail.com',
        jobTitle: 'Editor',
        shirtSize: 'L',
        title: 'Dr',
        suffix: 'II',
    },
    {
        firstName: 'Ira',
        lastName: 'Ferrulli',
        email: 'iferrullir@twitpic.com',
        jobTitle: 'Clinical Specialist',
        shirtSize: 'S',
        title: 'Ms',
        suffix: 'IV',
    },
    {
        firstName: 'Thomas',
        lastName: 'Holhouse',
        email: 'tholhouses@elpais.com',
        jobTitle: 'Web Developer II',
        shirtSize: '3XL',
        title: 'Rev',
        suffix: 'III',
    },
    {
        firstName: 'Ollie',
        lastName: 'Hackey',
        email: 'ohackeyt@friendfeed.com',
        jobTitle: 'Financial Analyst',
        shirtSize: '3XL',
        title: 'Honorable',
        suffix: 'III',
    },
    {
        firstName: 'Farris',
        lastName: 'Prydden',
        email: 'fpryddenu@edublogs.org',
        jobTitle: 'Mechanical Systems Engineer',
        shirtSize: 'XL',
        title: 'Rev',
        suffix: 'Jr',
    },
    {
        firstName: 'Sheelagh',
        lastName: 'Spira',
        email: 'sspirav@instagram.com',
        jobTitle: 'Civil Engineer',
        shirtSize: 'XS',
        title: 'Ms',
        suffix: 'Jr',
    },
    {
        firstName: 'Trixie',
        lastName: 'Sherrin',
        email: 'tsherrinw@answers.com',
        jobTitle: 'Technical Writer',
        shirtSize: 'XL',
        title: 'Dr',
        suffix: 'II',
    },
    {
        firstName: 'Maegan',
        lastName: 'Julien',
        email: 'mjulienx@webnode.com',
        jobTitle: 'Software Engineer III',
        shirtSize: 'S',
        title: 'Rev',
        suffix: 'III',
    },
    {
        firstName: 'Wendel',
        lastName: 'Macrow',
        email: 'wmacrowy@earthlink.net',
        jobTitle: 'Graphic Designer',
        shirtSize: 'M',
        title: 'Ms',
        suffix: 'II',
    },
    {
        firstName: 'Nickolai',
        lastName: 'Crummey',
        email: 'ncrummeyz@google.com.au',
        jobTitle: 'Web Designer II',
        shirtSize: 'S',
        title: 'Rev',
        suffix: 'Jr',
    },
    {
        firstName: 'Salaidh',
        lastName: 'Martinelli',
        email: 'smartinelli10@nih.gov',
        jobTitle: 'Database Administrator II',
        shirtSize: '2XL',
        title: 'Honorable',
        suffix: 'Sr',
    },
    {
        firstName: 'Ame',
        lastName: 'Mussen',
        email: 'amussen11@google.com.au',
        jobTitle: 'Human Resources Manager',
        shirtSize: 'XS',
        title: 'Mr',
        suffix: 'Jr',
    },
    {
        firstName: 'Adah',
        lastName: 'Thornebarrow',
        email: 'athornebarrow12@tiny.cc',
        jobTitle: 'Safety Technician I',
        shirtSize: '3XL',
        title: 'Mrs',
        suffix: 'II',
    },
    {
        firstName: 'Ekaterina',
        lastName: 'Duckworth',
        email: 'educkworth13@vinaora.com',
        jobTitle: 'Compensation Analyst',
        shirtSize: 'S',
        title: 'Honorable',
        suffix: 'II',
    },
];

export const SMALL_DATASET = [
    {
        firstName: 'Husein',
    },
    {
        firstName: 'Lindsey',
    },
    {
        firstName: 'Josefa',
    },
];
