name: 'Commit Version Changes'
description: 'Commit and push version changes with tag'
inputs:
    tag_name:
        required: true
        description: 'Tag name for the version'
    version_branch:
        required: false
        description: 'Branch name to commit version changes to (if provided, commits directly to this branch; otherwise creates a temporary version branch)'
outputs:
    version_commit_sha:
        description: 'SHA of the version commit'
        value: ${{ steps.commit_version.outputs.version_commit_sha }}
    created_version_branch:
        description: 'Created version branch name (only set if version_branch input is not provided)'
        value: ${{ steps.commit_version.outputs.version_branch }}
runs:
    using: composite
    steps:
        - name: Commit and push version changes
          id: commit_version
          shell: bash
          run: |
              TAG_NAME="${{ inputs.tag_name }}"
              VERSION_BRANCH_INPUT="${{ inputs.version_branch }}"

              if [ -z "$VERSION_BRANCH_INPUT" ]; then
                # Create a temporary version branch for the version commit
                CREATED_VERSION_BRANCH="temp-release-$(date +%s)"
                git checkout -b "$CREATED_VERSION_BRANCH"
                echo "version_branch=$CREATED_VERSION_BRANCH" >> $GITHUB_OUTPUT
                BRANCH_TO_PUSH="$CREATED_VERSION_BRANCH"
              else
                BRANCH_TO_PUSH="$VERSION_BRANCH_INPUT"
              fi

              # Stage version-related files
              git add package.json yarn.lock 2>/dev/null || true

              # Don't include [skip ci] in order to trigger tag push workflow (deployment) once release is published
              git commit -m "chore: bump version to $TAG_NAME"
              VERSION_COMMIT=$(git rev-parse HEAD)
              echo "version_commit_sha=$VERSION_COMMIT" >> $GITHUB_OUTPUT

              # Create tag pointing to the version commit
              git tag "$TAG_NAME" "$VERSION_COMMIT"

              # Push branch and tag together to trigger tag push workflow (deploy-release.yml)
              git push origin "$BRANCH_TO_PUSH" "$TAG_NAME"
          env:
              GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
