name: Bundle Size Update
on:
    push:
        branches:
            - main
env:
    NODE_VERSION: 22.x
permissions:
    packages: read
jobs:
    update-bundle-size:
        runs-on: ubuntu-latest
        steps:
            - name: Get GitHub App Access Token
              id: github-app-access-token
              uses: actions/create-github-app-token@v2
              with:
                  app-id: ${{ vars.GH_APP_ID_CHILI_FRONTEND_VERSION_MANAGER }}
                  private-key: ${{ secrets.GH_APP_PRIVATE_KEY_CHILI_FRONTEND_VERSION_MANAGER }}
                  owner: ${{ github.repository_owner }}
            - uses: FranzDiebold/github-env-vars-action@v2
            - uses: actions/checkout@v4
              with:
                  token: ${{ steps.github-app-access-token.outputs.token }}
            - name: Use Node ${{ env.NODE_VERSION }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  registry-url: 'https://npm.pkg.github.com'
                  scope: '@chili-publish'
            - name: install dependencies
              run: |
                  yarn install
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Build project
              run: yarn build

            - name: Get bundle size
              id: get_new_bundle_size
              run: |
                  new_bundle_size=$(du -sb dist/bundle.js | cut -f1)
                  echo "New size: $new_bundle_size"
                  echo "::set-output name=new_bundle_size::$new_bundle_size"
            - name: Update bundle-size.json
              run: |
                  new_bundle_size=${{ steps.get_new_bundle_size.outputs.new_bundle_size }}
                  echo "{ \"bundle_size\": $new_bundle_size }" > bundle-size.json
            - name: Commit and push updated bundle size
              run: |
                  git config --global user.name 'github-actions[bot]'
                  git config --global user.email user.email 'github-actions[bot]@users.noreply.github.com'
                  git add bundle-size.json
                  git commit -m "Update bundle size [skip ci]"
                  git push origin main --follow-tags
