name: Check PR description for JIRA ticket
on:
    pull_request:
        types: [opened, labeled]
jobs:
    check-description:
        runs-on: ubuntu-latest
        steps:
            - name: Check description of the Pull Request
              if: github.event.label.name != 'No JIRA ticket'
              uses: pkgacek/check-pr-description-for-jira-ticket@v1.6
