name: Comment deploy URL on PR open
on:
    pull_request:
        types: [opened]
jobs:
    comment:
        runs-on: k8s-rss-default
        steps:
            - uses: FranzDiebold/github-env-vars-action@v2
            - uses: actions/checkout@v3
            - name: 'Comment on PR'
              uses: actions/github-script@0.3.0
              if: github.event_name == 'pull_request'
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  script: |
                      const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
                      github.issues.createComment({ issue_number, owner, repo, body: 'PR can be checked at https://stgrafxstudiodevpublic.blob.core.windows.net/studio-ui/pr_builds/' + issue_number + '/index.html' });
                      github.issues.createComment({ issue_number, owner, repo, body: 'Coverage report can be checked at https://stgrafxstudiodevpublic.blob.core.windows.net/studio-ui/coverage_reports/' + issue_number + '/coverage.html' });
