name: Trigger the automated tests copy
on:
    pull_request:
        types: [labeled]
jobs:
    trigger-automated-tests:
        if: github.event.label.name == 'Ready for QA'
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - name: Get GitHub application JWT
            id: get-gh-app-jwt
            uses: ./.github/actions/get-gh-app-jwt
            with:
              gh-app-private-key: ${{ secrets.GH_APP_PRIVATE_KEY_CHILI_REPO_ACTIONS }}
              gh-app-id: ${{ vars.GH_APP_ID_CHILI_REPO_ACTIONS }}

          - uses: actions/checkout@v3
          - name: Get GitHub application installation access token
            id: get-gh-app-installation-access-token
            uses: ./.github/actions/get-gh-app-installation-access-token
            with:
              gh-app-jwt: ${{ steps.get-gh-app-jwt.outputs.gh-app-jwt }}
              gh-app-installation-id: ${{ vars.GH_APP_INSTALL_ID_CHILI_REPO_ACTIONS }}

          - uses: actions/checkout@v3
          - name: Trigger the automated tests
            uses: ./.github/actions/create-workflow-dispatch-event
            with:
              gh-access-token: ${{ steps.get-gh-app-installation-access-token.outputs.gh-app-installation-access-token }}
              gh-repo: chili-publish/editor-qa-framework
              gh-repo-workflow: parallel_run_trigger.yml
              gh-repo-workflow-inputs: '{"PR_NUMBER": "pr_builds=/${{ github.event.number }}", "SETTAG": "StudioUI"}'
