name: Trigger the automated tests
on:
    pull_request:
        types: [labeled]
permissions:
    contents: read
jobs:
    trigger-gauge-tests:
        if: github.event.label.name == 'Ready for QA'  || github.event.label.name == 'Skip QA'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7
              with:
                  persist-credentials: false
            - name: Skip tests notification
              if: github.event.label.name == 'Skip QA'
              run: |
                  echo "::notice::Automated tests are being skipped due to 'Skip QA' label"
                  exit 0
            - name: Create GitHub application token
              if: github.event.label.name == 'Ready for QA'
              id: create-github-app-token
              uses: actions/create-github-app-token@v3
              with:
                  client-id: ${{ vars.GH_APP_ID_CHILI_REPO_ACTIONS }}
                  private-key: ${{ secrets.GH_APP_PRIVATE_KEY_CHILI_REPO_ACTIONS }}

            - uses: actions/checkout@v7
              with:
                  persist-credentials: false

            - name: Trigger the gauge tests
              if: github.event.label.name == 'Ready for QA'
              uses: convictional/trigger-workflow-and-wait@924e4984551efec603bec665c0663332498c381a # v1.6.1
              with:
                  owner: chili-publish
                  repo: editor-qa-framework
                  github_token: ${{ steps.create-github-app-token.outputs.token }}
                  workflow_file_name: parallel_run_trigger.yml
                  ref: main
                  wait_interval: 10
                  propagate_failure: true
                  trigger_workflow: true
                  wait_workflow: true
                  client_payload: '{"PR_NUMBER": "pr_builds/${{ github.event.number }}", "SETTAG": "StudioUI"}'

    trigger-playwright-tests:
        if: github.event.label.name == 'Ready for QA'  || github.event.label.name == 'Skip QA'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7
              with:
                  persist-credentials: false
            - name: Skip tests notification
              if: github.event.label.name == 'Skip QA'
              run: |
                  echo "::notice::Automated tests are being skipped due to 'Skip QA' label"
                  exit 0
            - name: Create GitHub application token
              if: github.event.label.name == 'Ready for QA'
              id: create-github-app-token
              uses: actions/create-github-app-token@v3
              with:
                  client-id: ${{ vars.GH_APP_ID_CHILI_REPO_ACTIONS }}
                  private-key: ${{ secrets.GH_APP_PRIVATE_KEY_CHILI_REPO_ACTIONS }}

            - name: Trigger the Playwright tests in qa-playwright-framework
              if: github.event.label.name == 'Ready for QA'
              uses: convictional/trigger-workflow-and-wait@924e4984551efec603bec665c0663332498c381a # v1.6.1
              with:
                  owner: chili-publish
                  repo: qa-playwright-framework
                  github_token: ${{ steps.create-github-app-token.ouputs.token }}
                  workflow_file_name: run_tests_from_trigger.yml
                  ref: main
                  wait_interval: 10
                  propagate_failure: true
                  trigger_workflow: true
                  wait_workflow: true
                  client_payload: '{"PR_NUMBER": "pr_builds/${{ github.event.number }}", "SETTAG": "@STUDIOUI"}'
